server:
  port: 8080

spring:
  application:
    name: techstore-user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: email@gmail.com
    password: senha
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  secret: ${JWT_SECRET:algum-segredo-que-sera-variavel-de-ambiente}
  expiration: ${JWT_EXPIRATION:86400000}